# Generated by Django 6.0.2 on 2026-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
