# Generated by Django 6.0.2 on 2026-02-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_groupmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
    ]
