# Generated by Django 6.0.2 on 2026-02-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_groupmessage_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='doc_files/'),
        ),
    ]
