# Generated by Django 6.0.2 on 2026-02-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0004_groupmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='groupchat.groupmessage'),
        ),
    ]
