# Generated by Django 6.0.2 on 2026-02-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0005_groupmessage_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='reply_to',
        ),
    ]
